### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/home/bjf/LLaGA/checkpoints'

### ISSUE THREAD

**Issue by LaooBaoo** [VITA-Group/LLaGA#24]
great work but a little problem：
model_path="./checkpoints/cora.3/llaga-vicuna-7b-simteg-2-10-linear-projector_nc-lp"
model_base="lmsys/vicuna-7b-v1.5-16k" #meta-llama/Llama-2-7b-hf
mode="v1" # use 'llaga_llama_2' for llama and "v1" for others
dataset="cora" #test dataset
task="nc" #test task
emb="simteg"
use_hop=4
sample_size=10
template="HO" # or ND
output_path="/home/bjf/LLaGA/checkpoints"

python eval/eval_pretrain.py \
--model_path ${model_path} \
--model_base ${model_base} \
--conv_mode  ${mode} \
--dataset ${dataset} \
--pretrained_embedding_type ${emb} \
--use_hop ${use_hop} \
--sample_neighbor_size ${sample_size} \
--answers_file ${output_path} \
--task ${task} \
--cache_dir ../checkpoint \
--template ${template}

/home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_geometric/typing.py:68: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/libpyg.so)
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_geometric/typing.py:86: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_geometric/typing.py:97: UserWarning: An issue occurred while importing 'torch-cluster'. Disabling its usage. Stacktrace: /home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_cluster/_version_cuda.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(f"An issue occurred while importing 'torch-cluster'. "
/home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_geometric/typing.py:113: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: /home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_spline_conv/_version_cuda.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(
/home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_geometric/typing.py:124: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Loaded from /home/bjf/LLaGA/checkpoints/cora.3/llaga-vicuna-7b-simteg-2-10-linear-projector_nc-lp. Model Base: lmsys/vicuna-7b-v1.5-16k
Loading LLaGA from base model...
Loading checkpoint shards:   0%|                                                                                           | 0/2 [00:00<?, ?it/s]/home/bjf/anaconda3/envs/llaga/lib/python3.10/site-packages/transformers/modeling_utils.py:460: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location="cpu")
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.57s/it]
Some weights of LlagaLlamaForCausalLM were not initialized from the model checkpoint at lmsys/vicuna-7b-v1.5-16k and are newly initialized: ['model.mm_projector.weight', 'model.mm_projector.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/bjf/LLaGA/./model/builder.py:108: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mm_projector_weights = torch.load(os.path.join(model_path, 'mm_projector.bin'), map_location='cpu')
Load from local path
You shouldn't move a model that is dispatched using accelerate hooks.
/home/bjf/LLaGA/eval/eval_pretrain.py:108: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(data_path)
Load from dataset/cora/sampled_2_10_test.jsonl

Traceback (most recent call last):
  File "/home/bjf/LLaGA/eval/eval_pretrain.py", line 325, in <module>
    eval_model(args)
  File "/home/bjf/LLaGA/eval/eval_pretrain.py", line 122, in eval_model
    line_number = len(open(answers_file, 'r').readlines())
IsADirectoryError: [Errno 21] Is a directory: '/home/bjf/LLaGA/checkpoints'

no matter how i gear the path ,it report this error

**Comment by ChenRunjin** [comment]
the answers_file should be a path(jsonl) rather than a directory

**Comment by zujia-w** [comment]
请问你成功复现代码了？为什么我的结果是0
